/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"auditFlow" | "category" | "dashboard" | "department" | "employee" | "fullscreen-exit" | "fullscreen" | "inventory" | "inventoryRecord" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "material" | "outBoundApply" | "outBoundApplyApprove" | "outBoundApplyMenu" | "permission" | "purchase" | "purchaseApprove" | "purchaseMenu" | "role" | "scarceMaterial" | "search" | "statistics" | "stock" | "stockIn" | "stockInApprove" | "stockInMenu" | "stockOut" | "stockOutApprove" | "stockOutMenu" | "supplier" | "task" | "taskApprove" | "taskMenu" | "unit">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"auditFlow" | "category" | "dashboard" | "department" | "employee" | "fullscreen-exit" | "fullscreen" | "inventory" | "inventoryRecord" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "material" | "outBoundApply" | "outBoundApplyApprove" | "outBoundApplyMenu" | "permission" | "purchase" | "purchaseApprove" | "purchaseMenu" | "role" | "scarceMaterial" | "search" | "statistics" | "stock" | "stockIn" | "stockInApprove" | "stockInMenu" | "stockOut" | "stockOutApprove" | "stockOutMenu" | "supplier" | "task" | "taskApprove" | "taskMenu" | "unit">;
            default: string;
            required: true;
        };
    }>>, {
        name: "auditFlow" | "category" | "dashboard" | "department" | "employee" | "fullscreen-exit" | "fullscreen" | "inventory" | "inventoryRecord" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "material" | "outBoundApply" | "outBoundApplyApprove" | "outBoundApplyMenu" | "permission" | "purchase" | "purchaseApprove" | "purchaseMenu" | "role" | "scarceMaterial" | "search" | "statistics" | "stock" | "stockIn" | "stockInApprove" | "stockInMenu" | "stockOut" | "stockOutApprove" | "stockOutMenu" | "supplier" | "task" | "taskApprove" | "taskMenu" | "unit";
    }>;
  }
}
